{
 "title": "the monitor- windows - 47.101.133.33",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Gpu Mem Info",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket:\"monitor\")\n    |> range(start: -72h)\n    |> filter(fn: (r) => r._measurement == \"server_stat\" and r._field == \"GpuMemFree\")\n    |> aggregateWindow(every: 60s, fn: mean)"
    },
    {
     "query": "from(bucket:\"monitor\")\n    |> range(start: -72h)\n    |> filter(fn: (r) => r._measurement == \"server_stat\" and r._field == \"GpuMemUsed\")\n    |> aggregateWindow(every: 60s, fn: mean)"
    },
    {
     "query": "from(bucket:\"monitor\")\n    |> range(start: -72h)\n    |> filter(fn: (r) => r._measurement == \"server_stat\" and r._field == \"GpuMemTotal\")\n    |> aggregateWindow(every: 60s, fn: mean)"
    }
   ]
  },
  {
   "title": "Gpu Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 9, "y": 0 },
   "targets": [
    {
     "query": "from(bucket:\"monitor\")\n    |> range(start: -48h)\n    |> filter(fn: (r) => r._measurement == \"server_stat\" and r._field == \"GpuUtilization\")\n   |> aggregateWindow(every: 60s, fn: mean)"
    }
   ]
  },
  {
   "title": "Gpu Mem Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "query": "from(bucket:\"monitor\")\n    |> range(start: -72h)\n    |> filter(fn: (r) => r._measurement == \"server_stat\" and r._field == \"GpuMemUtilization\")\n   |> aggregateWindow(every: 60s, fn: mean)"
    }
   ]
  },
  {
   "title": "Cpu Percent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket:\"monitor\")\n    |> range(start: -72h)\n    |> filter(fn: (r) => r._measurement == \"server_stat\" and r._field == \"CpuPercent\")\n   |> aggregateWindow(every: 60s, fn: mean)"
    }
   ]
  },
  {
   "title": "Mem Percent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "query": "from(bucket:\"monitor\")\n    |> range(start: -72h)\n    |> filter(fn: (r) => r._measurement == \"server_stat\" and r._field == \"MemPercent\")\n   |> aggregateWindow(every: 60s, fn: mean)"
    }
   ]
  }
 ]
}